name: CI Mic Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assert mic simulation
        run: |
          sudo chmod +x simulation_test.sh
          sudo ./simulation_test.sh
